### ISSUE TITLE
Overlap seen with stringTests

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/build-a-nucleus#27]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.4

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/809 I see overlap of text and text/panels when using stringTest=double, long and RTL. 

**Visuals**
<img width="696" alt="Screen Shot 2022-06-08 at 12 34 56 PM" src="https://user-images.githubusercontent.com/87318828/172678539-550b5349-59e4-4b7e-a066-644c96e8a9c1.png">

<img width="498" alt="Screen Shot 2022-06-08 at 12 35 29 PM" src="https://user-images.githubusercontent.com/87318828/172671507-fc6fdb2e-c93c-471c-9e68-f0f98f65c02a.png">

<img width="1366" alt="Screen Shot 2022-06-08 at 12 36 46 PM" src="https://user-images.githubusercontent.com/87318828/172678615-1c715e5c-c2d7-42d0-bbb6-06bb6b33ca42.png">

<img width="953" alt="Screen Shot 2022-06-08 at 12 38 22 PM" src="https://user-images.githubusercontent.com/87318828/172678725-9287d542-8bc1-4d6c-84a9-0627f56b1c18.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-betaDecay.11/phet/build-a-nucleus_all_phet.html
Version: 1.0.0-betaDecay.11 2022-06-04 01:06:50 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36
Language: en-US
Window: 1365x694
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Luisav1** [comment]
Thanks @Nancy-Salpepi! This should be fixed in the commits above. You can check it and close it if it's fixed.

**Comment by Nancy-Salpepi** [comment]
Hi @Luisav1! Things are looking much better, but I'm still seeing overlap in the particle count panel with stringTest=double and stringTest=long.
<img width="182" alt="Screen Shot 2022-06-21 at 1 14 26 PM" src="https://user-images.githubusercontent.com/87318828/174859906-9f5da92a-23d3-4d25-911f-28f0e5a21bdc.png">
<img width="182" alt="Screen Shot 2022-06-21 at 1 15 24 PM" src="https://user-images.githubusercontent.com/87318828/174859930-2cd3f7b5-1eae-4314-8e8a-01e3b7dd36c3.png">

**Comment by Luisav1** [comment]
I missed that, thanks @Nancy-Salpepi! It should be fixed now.

**Comment by Nancy-Salpepi** [comment]
Looks good @Luisav1! Closing.
