### ISSUE TITLE
Beta decaying nuclide is slow to transform

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#53]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/828
When a nuclide is decaying, the change from one to the other is not immediate and the released particle can be some distance away before the change occurs. This is most easily seen when decaying a single neutron, but it happens with larger nucleuses too.

**Visuals**
![slowswitch](https://user-images.githubusercontent.com/41024075/187297772-8e15193c-56d3-4b56-9670-fde1297049d7.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-rc.8/phet/build-a-nucleus_all_phet.html
Version: 1.0.0-rc.8 2022-08-25 22:49:47 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Luisav1** [comment]
@ariel-phet @chrisklus We decided to speed up the animation a bit.

**Comment by Luisav1** [comment]
Thanks @KatieWoe! This should be fixed in the commit above. Could you please check it and confirm?

**Comment by KatieWoe** [comment]
This still seems to be happening in master. I pulled twice in incognito and am still seeing it.

**Comment by Luisav1** [comment]
Sorry, the change was in shred which was out of date but we updated and it should be fixed in phettest now. Could you please confirm that?

**Comment by KatieWoe** [comment]
I'm still seeing it. Sorry

**Comment by chrisklus** [comment]
For QA: Please close if this is fixed. The transformation should be 0.5 seconds instead of 1.0 seconds. Thanks!

**Comment by stemilymill** [comment]
It seems faster to me but I'm not confident enough to close. Might be best for @KatieWoe to take a look when she's back tomorrow.

**Comment by ariel-phet** [comment]
I took a look at RC.10 -- I think this speed looks pretty good (and definitely faster than before). @Katiewoe I am going to close, but feel free to reopen if you think this speed should be discussed at design meeting.
